ingress:
  enabled: false
  configNamespaceOverride: "default"

  ## Gitlab Ingress annotations
  ##
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'

  ## Gitlab Ingress hostnames
  ## Must be provided if Ingress is enabled
  ##
  hosts:
    - gitlab.example.com

  ## Gitlab Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  tls:
    - secretName: gitlab-server-tls
      hosts:
        - gitlab.example.com

persistence:
  ## This volume persists generated configuration files, keys, and certs.
  ##
  enabled: false
  size: 10Gi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: "default"
  accessMode: ReadWriteOnce


postgresql:
  persistence:
    enabled: false
    storageClass: "default"
    size: 10Gi

redis:
  persistence:
    enabled: false
    storageClass: "default"
    size: 10Gi

minio:
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  persistence:
    enabled: true
    storageClass: "default"
    size: 20Gi

sshPort: 22
httpPort: 80
httpsPort: 443


config:
  DEBUG: "true"
  #  GITLAB_ROOT_EMAIL: "gitlab-admin@gmail.com"
  #  GITLAB_HOST: gitlab.example.com

  GITLAB_ROOT_PASSWORD: "3Uhprz35WEYCmebz56dyvLciwvzQxz"
  GITLAB_SECRETS_DB_KEY_BASE: "kCFSUsLlyZETCpStxxKG"
  GITLAB_SECRETS_SECRET_KEY_BASE: "gPL3l6dQ4FXo6a9fwa6I"
  GITLAB_SECRETS_OTP_KEY_BASE: "SVEHkkfIViQ4xDuNN8LM"

  GITLAB_PORT: 443
  GITLAB_TIMEZONE: "Europe/Stockholm"
  GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "186f6cdcb713adEXAMPLETOKEN"

  GITLAB_SSH_HOST: "git.example.com"
  GITLAB_SSH_PORT: "22"


runner:
  enabled: false
  # gitlabUrl should point to the GITLAB_HOST
  gitlabUrl: "https://gitlab.example.com/ci/"
  registrationToken: "186f6cdcb713adEXAMPLETOKEN"
  cache:
    enabled: true
    accessKey: "AKIAIOSFODNN7EXAMPLE"
    secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

registry:
  enabled: false
  # authTokenRealm should point to the GITLAB_HOST
  authTokenRealm: "https://gitlab.example.com/jwt/auth"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
    hosts:
      - dhub.example.com

  persistence:
    enabled: false
