name: runner
version: 0.2.0
description: GitLab-ci runner
keywords:
- git
- ci
- deploy
home: https://about.gitlab.com
sources:
- https://hub.docker.com/r/gitlab/gitlab-runner/
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
maintainers:
- name: Sergey Nuzhdin
  email: ipaq.lw@gmail.com
